# Generated by Django 4.2.3 on 2024-02-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("apple", "Apple"),
                            ("asus", "Asus"),
                            ("hp", "HP"),
                            ("lenovo", "Lenovo"),
                        ],
                        max_length=6,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("ram", models.PositiveSmallIntegerField()),
                ("hdd", models.PositiveSmallIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("quantity", models.PositiveSmallIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ноутбук",
                "verbose_name_plural": "Ноутбуки",
                "ordering": ["brand"],
                "indexes": [
                    models.Index(fields=["brand"], name="challenges__brand_7b831a_idx")
                ],
            },
        ),
    ]
