# Generated by Django 4.2.3 on 2024-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_laptop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("text", models.CharField(max_length=5000)),
                ("author", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Опубликован"),
                            ("draft", "Не опубликован"),
                            ("ban", "Забанен"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("news", "Новости"),
                            ("travel", "Путешествия"),
                            ("food", "Еда"),
                            ("music", "Музыка"),
                            ("sport", "Спорт"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["published_at"], name="challenges__publish_45fc85_idx"
                    )
                ],
            },
        ),
    ]
