# Generated by Django 4.2.3 on 2024-02-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0003_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
