# Generated by Django 4.2.3 on 2024-02-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0004_alter_post_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("news", "Новости"),
                    ("travel", "Путешествия"),
                    ("food", "Еда"),
                    ("music", "Музыка"),
                    ("sport", "Спорт"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
