# Generated by Django 4.2.3 on 2024-02-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0005_alter_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="challenges__publish_45fc85_idx",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["created_at"], name="challenges__created_fb0ffc_idx"
            ),
        ),
    ]
